name: Build and Upload Artifacts (Java Maven)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up JDK (using Adoptium Temurin)
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Build the Java application using Maven
    - name: Build with Maven
      run: mvn clean install --no-transfer-progress  # Adjust Maven goals as needed

    # Step 5: Upload build artifacts (e.g., JAR file) to GitHub
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: java-build-artifacts   # Artifact name
        path: target/*.jar           # Path to the generated JAR or other artifacts in the 'target' directory
        ArtifactType: FilePath
